spring:

  application:
    name: sakilakiosk

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sakila_test
    username: root
    password: root
    platform: H2

  jpa:
    hibernate:

      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true

logging:

  config: classpath:log4j2.xml

---
spring:
  profiles: test

